version: '3'
services:
  web:
    image: nginx
    # command: rm /usr/share/nginx/html/index.html
    volumes:
      - ./templates:/etc/nginx/templates
      - .:/usr/share/nginx/html/
    ports:
      - "8090:80"
    environment:
      # - NGINX_HOST=foobar.com
      - NGINX_PORT=80